<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-3CBT8OQ" failures="1" tests="4" name="MyTest" time="18.01" errors="0" timestamp="2023-03-08T11:56:30 EET">
  <testcase classname="tests.LoginTests" name="loginTest" time="1.553"/>
  <testcase classname="tests.LoginTests" name="loginTest" time="0.878">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/]
at tests.LoginTests.loginTest(LoginTests.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="tests.LoginTests" name="loginTest" time="1.829"/>
  <testcase classname="tests.LoginTests" name="loginTest" time="6.269"/>
</testsuite> <!-- MyTest -->
